use_frameworks!

platform :ios, '8.0'

target 'HCDialogAlertView_Example' do
  pod 'HCDialogAlertView', :path => '../'

  target 'HCDialogAlertView_Tests' do
    inherit! :search_paths

    
  end
end
